.TH PROCINFO-NG 8 "2007-05-05" "v2.0" "Linux System Manual"

.SH NAME
procinfo \- display system statistics gathered from /proc

.SH SYNOPSIS
.B procinfo
[
.IR \-fdDSbrhv
] [
.IR \-n N
]

.SH DESCRIPTION
.B procinfo
gathers some system data from the
.B /proc
directory and prints it nicely formatted on the standard output
device.

The meanings of the fields are as follows:

.TP
.BI Memory:
See the man page for
.B free(1)

.TP
.BI Bootup:
The time the system was booted.

.TP
.BI Load\ average:
The average number of jobs running, followed by the number of runnable
processes and the total number of processes, followed by the PID
of the last process run. The pid of the last running process will probably
always be procinfo's PID.

.TP
.BI user:
The amount of time spent running jobs in user space.

.TP
.BI nice:
The amount of time spent running niced jobs in user space.

.TP
.BI system:
The amount of time spent running in kernel space.
.B Note:
the time spent servicing interrupts is not counted by the kernel (and
nothing that
.B procinfo
can do about it).

.TP
.BI idle:
The amount of time spent doing nothing.

.TP
.BI uptime:
The time that the system has been up. The above four should more or
less add up to this one.

.TP
.BI page\ in:
The number of disk blocks paged into core from disk. 1 block is equal to 1 kiB.

.TP
.BI page\ out:
The number of disk blocks paged out of core to disk. This includes regular disk-writes.

.TP
.BI swap\ in:
The number of memory pages paged in from swap.

.TP
.BI swap\ out:
The number of memory pages paged out to swap.

.TP
.BI context:
The number of context switches, either since bootup or per interval.

.TP
.BI Disk\ stats (hda,\ hdb,\ sda,\ sdb):
The number of reads and writes made to disks, whether CD-ROM, hard-drive, or USB.
Shows all disks if they either are an hdX or sdX, or if they have a non-zero read/write count.

.TP
.BI Interrupts:
Number of interrupts serviced since boot, or per interval, listed per IRQ.

.SH OPTIONS
.PD 0
.TP
.BI \-f
Run
.B procinfo
continuously full\-screen.

.TP
.BI \-n N
Pause N second between updates. This option implies
.B \-f. It may contain a decimal point.
The default is 5 seconds. When run by root with a pause of 0 seconds,
the program will run at the highest possible priority level.

.TP
.BI \-d
For memory, CPU times, paging, swapping, disk, context and interrupt stats,
display values per second rather than totals. This option implies
.B \-f.

.TP
.BI \-D
Same as
.B \-d,
except that memory stats are displayed as totals.

.TP
.BI \-S
When running with
.B \-d
or
.B \-D,
always show values per second, even when
running with
.B \-n N
with
.B N
greater than one second.

.TP
.BI \-b
Display numbers of blocks rather than numbers of I/O requests.

.TP
.BI \-r
This option adds an extra line to the memory info showing 'real' free
memory, just as free(1) does. The numbers produced assume that
Buffers and Cache are disposable.

.TP
.BI \-h
Print a brief help message.

.TP
.BI \-v
Print version info.

.SH INTERACTIVE COMMANDS
When running
.B procinfo
fullscreen, you can change its behaviour by pressing
.I d,
.I D,
.I S,
.I r
and
.I b,
which toggle the flags that correspond to their same\-named commandline-options.
In addition you can press
.I q
which quits the program.

.SH FILES
.TP
.BI /proc
The proc file system.

.SH BUGS
All of these statistics are taken verbatim from the kernel, without any scaling.
Any case where the kernel specifies that a particular field means something different
from how it is documented in this man-page, the kernel always wins.

Some features of the original procinfo were elided, as they were considered non-useful,
especially as many of them don't change anymore, and have better utilities for
listing/displaying them.

.SH SEE ALSO
free(1), uptime(1), w(1), init(8), proc(5).

.SH AUTHOR
Adam Schrotenboer <adam@tabris.net>
